# not using sudo
sudo: false

language: node_js
node_js:
- 'lts/*'

# setup the travis token
env:
  global:
  - secure: p7o70RUDLbPsm7UMtoXXpYUMtVnAgau2ic2RYeN+F6CG1WxWLKkLcuwRj/St5MxpQu5oVgsLCZdRdVhRu9BGgi9eDB/6DypBGemMJgs66912Q8bDazjynYVr8ZKy45LqllqvetdoG+QMRksD45rzLNKyKn0XwdbLLUbaGAY23V/YszE0J0oWuJL+h3Rb2M3uu5ls4aYKPobLdwLl8ispj8DysE5rssCZ9SoiWKFLApvVYKOEW/WRVvxpvl75dfKnVLhUPYUidGxfRpK4ibcoG83DLxsSTk0Huw7bP7Jnc16bo0ZdvEQyonbEeDBQoQs1BwpcQ6bVqsc3KypstXxm4BueCYzUJCXf1kEPWoRfzQL9OSUhqN2Yr6mKYwKG5R7g2IXmNyxX4ILLH9hQhV1upplu9/+CXA0QIybLlQQWb8tJrwxFnFmITvFl1JkcdFzguVRlCpRY0Q7KdlDI1hA243bW/Y8BYV/UdQZ6N+IfT9wgM/K+5qGjSJxweS8/pQAnuVNAhloM9Yt6wocf507jK8uiCYPJZZlQa5SBFazLoF0EybyV+Ds3jFJJSp+ORWrFUEZIZyJU/E+sMwsgSVpixj9u8uf4Y02hu5+EQzRHx46NVA2wl8YP4YF/SJqxNKWoyO2KsyqI8ZX4z3hTLhKnLu0LDliw3aPi01E5COGr8kg=

# main
script:
- yarn run lint
- yarn run test-ci --coverage --verbose

after_success:
# update gh-page only for master and not pull requests
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    chmod +x ./resources/scripts/update-gh-pages.sh; "./resources/scripts/update-gh-pages.sh";
  else echo "Not deploying artifacts for $TRAVIS_BRANCH"; fi
