# not using sudo
sudo: false

language: node_js
node_js:
- 'lts/*'

# main
script:
- yarn run lint
- yarn run test-ci --coverage --verbose

after_success:
# update gh-page only for master and not pull requests
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    chmod +x ./resources/scripts/update-gh-pages.sh; "./resources/scripts/update-gh-pages.sh";
  else echo "Not deploying artifacts for $TRAVIS_BRANCH"; fi
