# not using sudo
sudo: false

language: node_js
node_js:
- 'lts/*'

# setup the travis token
env:
  global:
  - secure: YAcdR6wxKsnwnB52OP6F2nqnNH9fx+FeTfTykWevhHLUz9D/W9zTYMQfEPb0shMlNECi1Wxmic2LLzfLFKVsdYSqm6+7/cUKNvA4+iPFIAZw6YJkWZAMqAwRz3E8+xcYtv1AU5hnqytUlVXPwEXQM2iYxoWYorsNmEn2C/zAye/F+d9WvVxvaJ1uYipt9WM9SWFqVUl2/2G/KUaf92xzYykoQ984RYMp6CjrKXRzlQ5dW7ncOwljNExmjaOOt0R202J4NxGcL8woAtXa2lmyjK27JB+5MsUx2IcRSFkqAMmV9708LElaWdSIjclflQJum6uYTGXKn8i8k3uOQNFeUYzPtLXT4hDlcZlaiFeV9W+d9vEw1NfPrzUdjeWNsl+sFsdruuLaOG+GUrTLyCcsLOLMJ4U6c98LlZS0MHk+6uPBpN8NI28iq+gLbVsxQ2OVNwCymQVnTb4h4kx2VSVJLmaznkBxBxMlRpS4xddSZ+WhG2dDy/cE4a3DIc7BkXhGQbaiCpboZgUEnEnvX9EPJ39TlplHqS4O35ZGvZDhEuLVrsdFHMev6s7e8n1yB7Umf68hrLV2X3JEyOTx7CXubLcQ/zREvA6gDBuU0JuYe292QtPdxxfrKXQ54epH4001E4/n4W0RRvpd+1DWKSLSJs1RS60EhXM+8duSgzpE2sI=

# main
script:
- yarn run lint
- yarn run test-ci --coverage --verbose

after_success:
# update gh-page only for master and not pull requests
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    chmod +x ./resources/scripts/update-gh-pages.sh; "./resources/scripts/update-gh-pages.sh";
  else echo "Not deploying artifacts for $TRAVIS_BRANCH"; fi
