# not using sudo
sudo: false

language: node_js
node_js:
- 'lts/*'

# setup the travis token
env:
  global:
    - secure: FlQG2gwF4QdlTZ6E/fSOw7FjF53r+3HaLfMCCcR5Qn9zpF0adqH/Dm/TeVuhqPnglVMMg3Xu71urtc+DlLe4QAXVL3CspWjZq4gdSiAs9SL6AdG2QV+oT3p8OIURrdNK3xdCwwzFOQ0fR4OPgjjW4YF4k8sLyrvVN9zyW4LDezItmnyBciU7jnOSeDrLDRVvYk2X3mSqPs0BZASVkBTlYSNxFrazcppeJjTJOBINd9mc0EGEP/F/0Z8Au+uqP1P2zIRshA7idIPuQ/Pxf3rf9p94C0RVDaD1mb4CGx4Gcm+294X9BFrNeGkHLTG5hPe+nmPQ6Gi2GKkerbREbDXJNk/0MLX7ECRTeKNgkUbUBhq+D9TLLIprWx9DAZDTxPuqTEaEIDkVD0AjOGO1BUuwhzAahEJG5NDDccI6IrSAwZ/a+8iLfsLGy/9R5mFovQd/NATBgOYchm046lZGtYAIgOMUgf9NO3mWmpBOsB2bffzkcmEb5A6dVK51u39y+WVgOU1ssVSULrxLcCRShrM/+apO5OEYnOGlsCiUJlG2ORS0a8oghp4Qe0x125ub1ShCoEvkf21R1KdQ6NTB4jSQKJ+BQjfKkDdvFAHLSPo0DQUHLan6If+KA0vAcU5WOA9l6RFsusjo/xiOQgW1T3NagsZKhEHDROmV3vK1GnLkfys=

# main
script:
- yarn run lint
- yarn run test-ci --coverage --verbose

after_success:
# update gh-page only for master and not pull requests
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    chmod +x ./resources/scripts/update-gh-pages.sh; "./resources/scripts/update-gh-pages.sh";
  else echo "Not deploying artifacts for $TRAVIS_BRANCH"; fi
