# not using sudo
sudo: false

language: node_js
node_js:
- 'lts/*'

# setup the travis token
env:
  global:
  - secure: pwraTTsw/nHIQIVYAwbpyI97Rq7aGSml6AS0RPm9yLHmS3lvxniDSTF5Wkq225oSqqeb+42Lu0Djhx7sA1wMcYyrmYFwcup73HZhaJ8G8oBuYkXPy1MbZvIURvwrbMNzM8r5jxoKXfOF5awlppMXcVQ+BrG8PvSrxPj8MeMh72WjD/dFx3mXnwOlFOA3rIK0/XdOTScOM8ct7yGTMUn7p8Ll4Arx/pwJMYfmlCVS7GbInh6g8QLZH3iEKv2ZpS07wulgDqF2/ITieNtVdFoRaDAUI/wBKkJKnphPnyj/aPyVLq8mnZYKw6xyoNEcM8Dxr+FGOet3w3HC8ctAgt3aNI4mw0nk+4UtqREK7LqWk/YvGibeWcLQX/jUJpSyd6dS7HMMcfWPFTpo93drWZs7QP/9dlgrvaeoivYFbLnFZluciOlPOTzIdfd7xWqDJWbGgeo2NOhBYBOhzEutCjU9QyqcY6FtMVGEVvZOeiMokI6URCQNZVZy04MFEbSJWF9M0xzCBG2p3TmtKoweWXYP9AZHElMIRilkdZ/YJzTlLIZS+1shG/A7EflDFLJmUjBVAE0gS5NPZF0olT6N1neFgIZpTDVchHfphVpMwqeYQcKWr0Brv4Y0VYcngF1jsimrhdYdcaPQeNDeKjQregFwW4eDrraurJCOOtc5lkGVJQI=

# main
script:
- yarn run lint
- yarn run test-ci --coverage --verbose

after_success:
# update gh-page only for master and not pull requests
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    chmod +x ./resources/scripts/update-gh-pages.sh; "./resources/scripts/update-gh-pages.sh";
  else echo "Not deploying artifacts for $TRAVIS_BRANCH"; fi
