# not using sudo
sudo: false

language: node_js
node_js:
- 'lts/*'

# setup the travis token
env:
  global:
  - secure: aTGKYmbhwx/KCG1ftu6DiIiv131ppcWW0E3ll1p+XucHVJI1O8nc6HpBvk1y//PZOoxr2sfGlMxYBwRD1n+ieHroekbR7PcGORC1/CadfwDvynK5GLTQYL+M8cfUf/jOKP0Tc7Kj2jna2jEtc8sXK+othYcXxWwOXm+rChjqSpNjdndBTtcNFuGixWI6XZ3xYxwWEquse6Kw2Kg/LH+C/a9CH9SYAvUzh167OdR8Hcg51bZH8SuJm1NIRvTnygNo2sN4RfWJJc7t8PChT18Wvhwu9kgrl/9scNuxKo8fn92NsMBFLcWUc1hKJ1DFIsYBI4zJZbetIq71dM1kii4zqefVAasP+c8tGSjOuwqoxldOx+StQxt5rmm5rIyq41HoN87krWkWAj8JUOott8+azghmDTjR03AWcsIhvgnC8nHitZHZdTtS08A5By2WDhzf/D0xVfHUW2Ni8a71cpgXtT45D/6ueZQjT5naxZDfBb8wvoEJdx8SoDYsr7hCLe4e29/yMXY9MG7qY3JPN6kyWzc1jOktk4+bFYC+x5m5XXONuUlUcOcGMAJ2wabkY99x3zTKefHAmhob6GyB5HxW46dSaZ2qGhapDzaWfj/lgoCi9mn4cDIXrED4vphAoRnufYt5fmtYohyC48QWz4BXFzyJoOzHseZvrIgTn9/vbxw=

# main
script:
- yarn run lint
- yarn run test-ci --coverage --verbose

after_success:
# update gh-page only for master and not pull requests
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    chmod +x ./resources/scripts/update-gh-pages.sh; "./resources/scripts/update-gh-pages.sh";
  else echo "Not deploying artifacts for $TRAVIS_BRANCH"; fi
